import Foundation

/// Popular websites you can open by name: "open Netflix", "go to Hacker News", "open Gmail in Safari".
/// (Services with a search link — Google, YouTube, Amazon… — are in `AppCommands.builtIn`.)
public enum Websites {
    static func site(_ name: String, _ url: String, _ aliases: String...) -> AppTarget {
        AppTarget(name: name, aliases: aliases, url: url)
    }

    public static let all: [AppTarget] = [
        // Google
        site("Google Docs", "https://docs.google.com", "docs"),
        site("Google Sheets", "https://sheets.google.com", "sheets"),
        site("Google Slides", "https://slides.google.com", "slides"),
        site("Google Meet", "https://meet.google.com", "meet"),
        site("Google Photos", "https://photos.google.com", "photos"),
        site("Google Keep", "https://keep.google.com", "keep"),
        site("Google Translate", "https://translate.google.com", "translate"),
        site("Google News", "https://news.google.com"),
        site("Google Scholar", "https://scholar.google.com", "scholar"),
        site("Gemini", "https://gemini.google.com", "google gemini", "bard"),
        // Work
        site("Outlook", "https://outlook.live.com", "outlook web", "hotmail"),
        site("Office", "https://www.office.com", "microsoft office", "office 365", "microsoft 365"),
        site("OneDrive", "https://onedrive.live.com", "one drive"),
        site("Dropbox", "https://www.dropbox.com"),
        site("Box", "https://app.box.com"),
        site("iCloud", "https://www.icloud.com", "i cloud"),
        site("Slack Web", "https://app.slack.com", "slack website"),
        site("Microsoft Teams Web", "https://teams.microsoft.com", "teams website"),
        site("Zoom Web", "https://zoom.us", "zoom website"),
        site("Calendly", "https://calendly.com"),
        site("Trello", "https://trello.com"),
        site("Asana", "https://app.asana.com"),
        site("Monday", "https://monday.com", "monday dot com"),
        site("ClickUp", "https://app.clickup.com", "click up"),
        site("Jira", "https://www.atlassian.com/software/jira"),
        site("Confluence", "https://www.atlassian.com/software/confluence"),
        site("Airtable", "https://airtable.com"),
        site("Miro", "https://miro.com"),
        site("Canva", "https://www.canva.com"),
        site("Grammarly", "https://app.grammarly.com"),
        site("Loom", "https://www.loom.com"),
        site("Salesforce", "https://login.salesforce.com"),
        site("HubSpot", "https://app.hubspot.com", "hub spot"),
        site("Zendesk", "https://www.zendesk.com"),
        site("Intercom", "https://app.intercom.com"),
        site("Stripe", "https://dashboard.stripe.com", "stripe dashboard"),
        site("Shopify", "https://admin.shopify.com", "shopify admin"),
        site("QuickBooks", "https://qbo.intuit.com", "quick books"),
        site("DocuSign", "https://app.docusign.com", "docu sign"),
        // Developers & AI
        site("GitLab", "https://gitlab.com", "git lab"),
        site("Stack Overflow", "https://stackoverflow.com", "stackoverflow"),
        site("Hacker News", "https://news.ycombinator.com", "hn", "y combinator news"),
        site("Product Hunt", "https://www.producthunt.com"),
        site("Hugging Face", "https://huggingface.co", "huggingface"),
        site("Kaggle", "https://www.kaggle.com"),
        site("LeetCode", "https://leetcode.com", "leet code"),
        site("Vercel", "https://vercel.com/dashboard"),
        site("Netlify", "https://app.netlify.com"),
        site("AWS Console", "https://console.aws.amazon.com", "aws", "amazon web services"),
        site("Google Cloud Console", "https://console.cloud.google.com", "google cloud", "gcp"),
        site("Azure Portal", "https://portal.azure.com", "azure"),
        site("Cloudflare", "https://dash.cloudflare.com"),
        site("Supabase", "https://supabase.com/dashboard"),
        site("Replit", "https://replit.com"),
        site("CodePen", "https://codepen.io", "code pen"),
        site("npm", "https://www.npmjs.com", "npm js"),
        site("arXiv", "https://arxiv.org", "archive", "arxiv"),
        site("Copilot", "https://copilot.microsoft.com", "microsoft copilot"),
        site("Grok", "https://grok.com"),
        site("Mistral", "https://chat.mistral.ai", "le chat"),
        // Social & messaging
        site("Facebook", "https://www.facebook.com", "fb"),
        site("Instagram", "https://www.instagram.com", "insta"),
        site("Threads", "https://www.threads.net"),
        site("TikTok", "https://www.tiktok.com", "tik tok"),
        site("Pinterest", "https://www.pinterest.com"),
        site("Snapchat", "https://www.snapchat.com"),
        site("Messenger", "https://www.messenger.com", "facebook messenger"),
        site("Telegram Web", "https://web.telegram.org", "telegram"),
        site("Discord Web", "https://discord.com/app", "discord website"),
        site("Bluesky", "https://bsky.app", "blue sky"),
        site("Quora", "https://www.quora.com"),
        site("Medium", "https://medium.com"),
        site("Substack", "https://substack.com"),
        site("Tumblr", "https://www.tumblr.com"),
        // Entertainment
        site("Prime Video", "https://www.primevideo.com", "amazon prime video", "prime"),
        site("Disney Plus", "https://www.disneyplus.com", "disney+", "disney"),
        site("Hulu", "https://www.hulu.com"),
        site("Max", "https://www.max.com", "hbo max", "hbo"),
        site("Hotstar", "https://www.hotstar.com", "jio hotstar", "disney hotstar"),
        site("Twitch", "https://www.twitch.tv"),
        site("Apple Music", "https://music.apple.com"),
        site("SoundCloud", "https://soundcloud.com", "sound cloud"),
        site("IMDb", "https://www.imdb.com", "imdb", "i m d b"),
        site("Goodreads", "https://www.goodreads.com", "good reads"),
        // News & info
        site("BBC", "https://www.bbc.com", "bbc news"),
        site("CNN", "https://www.cnn.com"),
        site("New York Times", "https://www.nytimes.com", "nytimes", "the new york times"),
        site("The Guardian", "https://www.theguardian.com", "guardian"),
        site("Bloomberg", "https://www.bloomberg.com"),
        site("Reuters", "https://www.reuters.com"),
        site("The Verge", "https://www.theverge.com", "verge"),
        site("TechCrunch", "https://techcrunch.com", "tech crunch"),
        site("ESPN", "https://www.espn.com"),
        site("Cricbuzz", "https://www.cricbuzz.com", "cric buzz"),
        site("Weather", "https://weather.com", "weather dot com", "the weather channel"),
        // Shopping, travel, everyday
        site("eBay", "https://www.ebay.com", "ebay"),
        site("Walmart", "https://www.walmart.com"),
        site("Target", "https://www.target.com"),
        site("Costco", "https://www.costco.com"),
        site("Etsy", "https://www.etsy.com"),
        site("Best Buy", "https://www.bestbuy.com", "bestbuy"),
        site("Flipkart", "https://www.flipkart.com", "flip kart"),
        site("Myntra", "https://www.myntra.com"),
        site("Swiggy", "https://www.swiggy.com"),
        site("Zomato", "https://www.zomato.com"),
        site("DoorDash", "https://www.doordash.com", "door dash"),
        site("Uber Eats", "https://www.ubereats.com"),
        site("Instacart", "https://www.instacart.com", "insta cart"),
        site("Airbnb", "https://www.airbnb.com", "air bnb"),
        site("Booking", "https://www.booking.com", "booking dot com"),
        site("Expedia", "https://www.expedia.com"),
        site("Google Flights", "https://www.google.com/travel/flights", "flights"),
        site("Uber", "https://m.uber.com"),
        site("Zillow", "https://www.zillow.com"),
        site("Yelp", "https://www.yelp.com"),
        site("Tripadvisor", "https://www.tripadvisor.com", "trip advisor"),
        site("Craigslist", "https://www.craigslist.org"),
        site("PayPal", "https://www.paypal.com", "pay pal"),
        // Learning & jobs
        site("Coursera", "https://www.coursera.org"),
        site("Udemy", "https://www.udemy.com"),
        site("Khan Academy", "https://www.khanacademy.org"),
        site("Duolingo", "https://www.duolingo.com"),
        site("Indeed", "https://www.indeed.com"),
        site("Glassdoor", "https://www.glassdoor.com", "glass door"),
    ]

    /// Browsers you can name: "open Gmail in Chrome".
    public static let browserNames: Set<String> = [
        "chrome", "google chrome", "safari", "arc", "dia", "firefox", "brave", "brave browser", "edge",
        "microsoft edge", "opera", "vivaldi", "orion", "zen",
    ]
}
