import AppKit
import Carbon.HIToolbox

/// Puts text at the cursor of whatever app is focused, via the clipboard + a synthetic ⌘V.
/// Works anywhere normal paste works; no per-app integrations. Needs Accessibility permission.
@MainActor
final class TextInjector {
    /// Clipboard managers skip items marked with these types (nspasteboard.org convention).
    private static let transientTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]
    private var pendingRestore: [NSPasteboardItem]?
    private var restoreTask: Task<Void, Never>?

    func insert(_ text: String, restoreClipboard: Bool) async {
        // Typing into Evoo's own window (the welcome tour's try-it box): insert directly, no simulated ⌘V.
        if ScreenText.evooIsFrontmost, let view = NSApp.keyWindow?.firstResponder as? NSTextView {
            view.insertText(text, replacementRange: view.selectedRange())
            #if DEBUG
            try? view.string.write(toFile: "/tmp/evoo-selftest.txt", atomically: true, encoding: .utf8)
            #endif
            return
        }
        let pasteboard = NSPasteboard.general
        // A dictation right after another: the user's clipboard is still the one saved last time.
        let saved = restoreClipboard ? (pendingRestore ?? snapshot(pasteboard)) : []

        pasteboard.clearContents()
        pasteboard.declareTypes([.string] + Self.transientTypes, owner: nil)
        pasteboard.setString(text, forType: .string)
        for type in Self.transientTypes { pasteboard.setData(Data(), forType: type) }
        let ourChange = pasteboard.changeCount

        postPaste()

        guard restoreClipboard else { return }
        // Returns right away (the text is in); the user's clipboard comes back once the app has read ours.
        pendingRestore = saved
        restoreTask?.cancel()
        restoreTask = Task { [weak self] in
            try? await Task.sleep(for: .milliseconds(400))
            guard !Task.isCancelled else { return }
            self?.pendingRestore = nil
            // If the user copied something in the meantime, leave it alone.
            guard pasteboard.changeCount == ourChange else { return }
            pasteboard.clearContents()
            if !saved.isEmpty { pasteboard.writeObjects(saved) }
        }
    }

    /// Delete key — removes the current selection.
    func deleteSelection() {
        postKey(CGKeyCode(kVK_Delete), flags: [])
    }

    /// ⌘Z — "undo that".
    func undo() {
        postKey(CGKeyCode(kVK_ANSI_Z), flags: .maskCommand)
    }

    /// Return — "press enter" (sends the message in chat apps).
    func pressReturn() async {
        try? await Task.sleep(for: .milliseconds(60)) // let the paste land first
        postKey(CGKeyCode(kVK_Return), flags: [])
    }

    private func postKey(_ key: CGKeyCode, flags: CGEventFlags) {
        let source = CGEventSource(stateID: .combinedSessionState)
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        down?.flags = flags
        up?.flags = flags
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    private func postPaste() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let v = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    private func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }
}
